run:
  timeout: 3m
  modules-download-mode: readonly

linters:
  enable:
    - errname
    - gofmt
    - goimports
    - sqlclosecheck
    - stylecheck
    - unconvert
    - unparam

issues:
  fix: true
