// Code generated by MockGen. DO NOT EDIT.
// Source: pgmq.go
//
// Generated by this command:
//
//	mockgen --source=pgmq.go --destination mocks/pgmq.go --package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
